version: "3.8"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1vol
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mahathir
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: admin
    volumes:
      - "mongo-data1:/data/db"
  mongodb2:
    image: mongo:latest
    container_name: mongodb2vol
    ports:
      - "27018:27017"
    environment:      
      MONGO_INITDB_ROOT_USERNAME: mahathir
      MONGO_INITDB_ROOT_PASSWORD: 12345678y
      MONGO_INITDB_DATABASE: admin
    volumes:
      - type: volume
        source: mongo-data2
        target: "/data/db"
        read_only: false

volumes:
  mongo-data1:
    name: mongo-data1
  mongo-data2:
    name: mongo-data2