version: "3.8"

services:

  mongodb-example:
    image: mongo:latest
    container_name: mongodb-restart
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: khannedy
      MONGO_INITDB_ROOT_PASSWORD: khannedy
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-restart
    restart: always
    depends_on:
      - "mongodb-example"
    ports:
      - "8081:8081"  
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mahathir
      ME_CONFIG_MONGODB_ADMINPASSWORD: mahathir
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network_example

networks:
  network_example:
    name: network_restart
    driver: bridge    
