version: "3.8"

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mahathir
      MONGO_INITDB_ROOT_PASSWORD: mahathir
      MONGO_INITDB_DATABASE: admin
    networks:
      - network_example

networks:
  network_example:
    name: network_example
    driver: bridge